package net.minecraft.server;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;

public class WorldGenFeatureBastionUnits {

    public static void a() {}

    static {
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/center_pieces"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/center_pieces/center_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/center_pieces/center_1", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/center_pieces/center_2", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/pathways"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/pathways/pathway_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/pathways/pathway_wall_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/walls/wall_bases"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/walls/wall_base", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/walls/connected_wall", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/stages/stage_0"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_0_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_0_1", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_0_2", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_0_3", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/stages/stage_1"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_1_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_1_1", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_1_2", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_1_3", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/stages/rot/stage_1"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/rot/stage_1_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/stages/stage_2"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_2_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_2_1", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/stages/stage_3"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_3_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_3_1", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_3_2", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/stages/stage_3_3", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/fillers/stage_0"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/fillers/stage_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/edges"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/edges/edge_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/wall_units"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/wall_units/unit_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/edge_wall_units"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/wall_units/edge_0_large", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/ramparts"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/ramparts/ramparts_0", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/ramparts/ramparts_1", ProcessorLists.u), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/ramparts/ramparts_2", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/large_ramparts"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/ramparts/ramparts_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/units/rampart_plates"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/units/rampart_plates/plate_0", ProcessorLists.u), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
    }
}
