package net.minecraft.server;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;

public class WorldGenFeatureBastionHoglinStable {

    public static void a() {}

    static {
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/starting_pieces"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/starting_stairs_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/starting_stairs_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/starting_stairs_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/starting_stairs_3", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/starting_stairs_4", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/mirrored_starting_pieces"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/stairs_0_mirrored", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/stairs_1_mirrored", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/stairs_2_mirrored", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/stairs_3_mirrored", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/starting_pieces/stairs_4_mirrored", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/wall_bases"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/walls/wall_base", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/walls"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/walls/side_wall_0", ProcessorLists.v), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/walls/side_wall_1", ProcessorLists.v), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/stairs"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_1_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_1_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_1_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_1_3", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_1_4", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_2_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_2_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_2_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_2_3", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_2_4", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_3_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_3_1", ProcessorLists.w), 1), new Pair[]{Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_3_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_3_3", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/stairs/stairs_3_4", ProcessorLists.w), 1)}), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/small_stables/inner"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/inner_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/inner_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/inner_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/inner_3", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/small_stables/outer"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/outer_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/outer_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/outer_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/small_stables/outer_3", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/large_stables/inner"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/inner_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/inner_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/inner_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/inner_3", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/inner_4", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/large_stables/outer"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/outer_0", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/outer_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/outer_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/outer_3", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/large_stables/outer_4", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/posts"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/posts/stair_post", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/posts/end_post", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/ramparts"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/ramparts/ramparts_1", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/ramparts/ramparts_2", ProcessorLists.w), 1), Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/ramparts/ramparts_3", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/rampart_plates"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/rampart_plates/rampart_plate_1", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
        WorldGenFeaturePieces.a(new WorldGenFeatureDefinedStructurePoolTemplate(new MinecraftKey("bastion/hoglin_stable/connectors"), new MinecraftKey("empty"), ImmutableList.of(Pair.of(WorldGenFeatureDefinedStructurePoolStructure.b("bastion/hoglin_stable/connectors/end_post_connector", ProcessorLists.w), 1)), WorldGenFeatureDefinedStructurePoolTemplate.Matching.RIGID));
    }
}
